spring.application.name=project-service
#spring.config.import=optional:configserver:http://dc-config-server:8888
server.port=8082

# File Upload Limits (50MB)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
