apiVersion: apps/v1
kind: Deployment
metadata:
  name: dc-dockerfile-service
  namespace: dockercraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dc-dockerfile-service
  template:
    metadata:
      labels:
        app: dc-dockerfile-service
    spec:
      containers:
      - name: dockerfile-service
        image: malekkhmiri/dockergeneration-dockerfile-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        envFrom:
        - configMapRef:
            name: common-config
        - secretRef:
            name: common-secrets
        env:
        - name: SERVER_PORT
          value: "8083"
        - name: OLLAMA_URL
          value: "http://dc-ollama:11434"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dc-dockerfile-service
  namespace: dockercraft
spec:
  selector:
    app: dc-dockerfile-service
  ports:
  - port: 8083
    targetPort: 8083
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: dockercraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
