server:
  port: 9016
 
spring:
  application:
    name: dockerfile-service
  datasource:
    url: jdbc:postgresql://db:5432/pipeline_automation
    username: pfe
    password: pfe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
 
