FROM ollama/ollama:latest

# On expose le port 8080
ENV OLLAMA_HOST=0.0.0.0:8080

# On lance ollama en arrière-plan, on attend qu'il soit prêt, on pull le modèle, puis on arrête
RUN (ollama serve &) && \
    sleep 5 && \
    ollama pull qwen2.5-coder:3b && \
    pkill ollama

ENTRYPOINT ["ollama", "serve"]
