spring.application.name=dockerfile-service
spring.config.import=optional:configserver:http://dc-config-server:8888
server.port=8083

# Utilise Qwen2.5-Coder pour sa précision technique
ollama.model=qwen2.5-coder:3b
ollama.url=http://dc-ollama:11434

