spring.application.name=dockerfile-service
server.port=8080

# Utilise Qwen2.5-Coder pour sa précision technique
ollama.model=qwen2.5-coder:3b
ollama.url=${OLLAMA_URL:http://dc-ollama:11434}

# Stability Fixes for Cloud Run
spring.cloud.config.enabled=false
eureka.client.enabled=false
spring.cloud.discovery.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework=INFO

